export const BASIC_BOTTOM_MODAL_ANIMATION_DURATION = 1000;
export const NOW = 0;
export const BASIC_TOAST_MODAL_ANIMATION_DURATION = 3000;
export const BASIC_TOAST_DURATION = 6000;
export const CONTENTS_CLASS_NAME = 'modal-contents';
export const BASIC_PADDING = '2rem 1.5rem';
export const BASIC_BORDER_RADIUS = '0.625rem';
export const BASIC_MODAL_BACKGROUND_COLOR = '#ffff';
export const BASIC_BACK_DROP_BACKGROUND_COLOR = '#5959599b';
